name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install neovim
        run: |
          mkdir -p neovim
          curl -sL "https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/neovim"
      - name: test
        run: |
          export PATH="${PWD}/neovim/bin:${PATH}"
          export VIM="${PWD}/neovim/share/nvim/runtime"
          make test

  docs:
    needs: test
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: lazy-nix-helper.nvim
          version: "Neovim >= 0.9.0?"
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
