name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          make test

  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: lazy-nix-helper.nvim
          version: "Neovim >= 0.9.0?"
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
